# Generated by Django 3.2.5 on 2021-08-07 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='enter your first_name', max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(help_text='enter your last_name', max_length=100, verbose_name='last_name')),
                ('email', models.CharField(help_text='enter your email', max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(help_text='enter your phone', max_length=100, verbose_name='phone')),
                ('date_of_birth', models.DateField(help_text='enter your date_of_birth', verbose_name='date_of_birth')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(help_text='enter your lat', verbose_name='lat')),
                ('lng', models.FloatField(help_text='enter your lng', verbose_name='lng')),
                ('country', models.CharField(help_text='enter your country', max_length=50, verbose_name='country')),
                ('city', models.CharField(help_text='enter your city', max_length=50, verbose_name='city')),
                ('State', models.CharField(help_text='enter your state', max_length=50, verbose_name='state')),
                ('description', models.TextField(help_text='enter your description', verbose_name='description')),
                ('zip_code', models.CharField(help_text='enter your zop_cide', max_length=50, verbose_name='zip_code')),
                ('Alley', models.CharField(help_text='enter your Alley', max_length=50, verbose_name='Alley')),
                ('Plaque', models.CharField(help_text='enter your plaque', max_length=50, verbose_name='plaque')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
