# Generated by Django 3.2.5 on 2021-08-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210807_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.FloatField(blank=True, help_text='enter your lat', null=True, verbose_name='lat'),
        ),
    ]
