# Generated by Django 3.2.5 on 2021-08-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_lat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('city',), 'verbose_name_plural': 'Address'},
        ),
    ]
