# Generated by Django 3.2.5 on 2021-08-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_address_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.FloatField(blank=True, help_text='enter your lng', null=True, verbose_name='lng'),
        ),
    ]
