# Generated by Django 3.2.5 on 2021-08-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
