# Generated by Django 3.2.5 on 2021-08-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(help_text='enter your address', on_delete=django.db.models.deletion.CASCADE, to='customer.address', verbose_name='address'),
        ),
    ]
