# Generated by Django 3.2.5 on 2021-08-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=111, max_length=100, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
