# Generated by Django 3.2.5 on 2021-08-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(blank=True, help_text='enter your address', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.address', verbose_name='address'),
        ),
    ]
