# Generated by Django 3.2.5 on 2021-08-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='enter your phone', max_length=100, verbose_name='phone'),
        ),
    ]
