# Generated by Django 3.2.5 on 2021-08-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210802_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_expired', models.BooleanField(default=False)),
                ('logical_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('title', models.CharField(help_text='enter your tittle', max_length=100, verbose_name='title')),
                ('Deduction_from_the_price', models.IntegerField(help_text='enter your Deduction_from_the_price', verbose_name='Deduction_from_the_price')),
                ('Cash', models.IntegerField(help_text='enter your Deduction_from_the_price', verbose_name='Deduction_from_the_price')),
                ('description', models.TextField(help_text='Additional product description', verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(help_text='discount', on_delete=django.db.models.deletion.CASCADE, to='product.discount', verbose_name='discount'),
        ),
    ]
