# Generated by Django 3.2.5 on 2021-08-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_discount_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='logical_delete',
        ),
    ]
