# Generated by Django 3.2.5 on 2021-08-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210807_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='logical_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
