# Generated by Django 3.2.5 on 2021-08-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210807_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='Cash',
            field=models.IntegerField(default=0, help_text='enter your Cash', verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Deduction_from_the_price',
            field=models.IntegerField(default=0, help_text='enter your Deduction_from_the_price', verbose_name='Deduction_from_the_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='discount', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount', verbose_name='discount'),
        ),
    ]
