# Generated by Django 3.2.5 on 2021-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210807_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='Cash',
            field=models.DecimalField(decimal_places=2, default=0, help_text='enter your Cash', max_digits=3, verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Deduction_from_the_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='enter your Deduction_from_the_price', max_digits=3, verbose_name='Deduction_from_the_price'),
        ),
    ]
