# Generated by Django 3.2.5 on 2021-08-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210807_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='Cash',
            field=models.IntegerField(help_text='enter your Cash', verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Deduction_from_the_price',
            field=models.IntegerField(help_text='enter your Deduction_from_the_price', verbose_name='Deduction_from_the_price'),
        ),
    ]
