# Generated by Django 3.2.5 on 2021-08-08 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_auto_20210807_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('user', models.ForeignKey(help_text='name is user', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='enter your prices', max_digits=10, verbose_name='price')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(help_text='orderes', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='orders')),
                ('product', models.ForeignKey(help_text='products', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product', verbose_name='product')),
            ],
        ),
    ]
