# Generated by Django 3.2.5 on 2021-08-08 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='enter your code', max_length=30, unique=True, verbose_name='code')),
                ('valid_from', models.DateTimeField(verbose_name='valid_from')),
                ('valid_to', models.DateTimeField(verbose_name='valid_to')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
        ),
    ]
